// Outrank only allows a single integration, so we use its publish webhook (not
// the pull API). Each published article is pushed to us and persisted in Vercel
// Blob as two objects:
//   - blog/index.json             array of lightweight card summaries
//   - blog/posts/<slug>.json      full article (html, markdown, meta)
//
// The blog routes are FULLY STATIC (`force-static`, `dynamicParams = false`).
// They read Blob here only at build time; user requests are served from the
// prebuilt output and never trigger a live render or a live fetch. On publish,
// the webhook triggers a redeploy (Vercel deploy hook) so the freshly-built
// site includes the new/updated article. This avoids Vercel's serverless
// live-render failures we hit with dynamic/ISR blog rendering.

export const INDEX_BLOB_PATH = 'blog/index.json'

export function postBlobPath(slug: string): string {
  return `blog/posts/${slug}.json`
}

function blobBaseUrl(): string {
  return (process.env.BLOB_BASE_URL || '').replace(/\/+$/, '')
}

export type BlogArticle = {
  id: string
  slug: string
  title: string
  meta_description: string
  html: string
  content_markdown: string
  image_url: string
  tags: string[]
  created_at: string
  updated_at: string
  reading_time_minutes: number
}

export type BlogArticleSummary = Omit<BlogArticle, 'html' | 'content_markdown'>

export function isBlogConfigured(): boolean {
  return Boolean(blobBaseUrl())
}

export function formatBlogDate(iso: string | null): string {
  if (!iso) return ''
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(date)
}

export function articleExcerpt(
  article: Pick<BlogArticleSummary, 'meta_description'>,
): string {
  return (article.meta_description || '').trim()
}

// Unique per build/process. Appended to Blob read URLs so each rebuild reads
// fresh from origin instead of a stale entry in Vercel's persistent Data Cache
// or the Blob CDN edge — the blog is rebuilt on publish, so freshness at build
// time is what matters. Shared across all reads in one build (dedupes fetches).
const BUILD_CACHE_BUSTER = Date.now().toString(36)

// Build-time read. `force-cache` keeps the blog routes statically renderable;
// they are regenerated by a redeploy on publish, so there is no need to
// revalidate at runtime.
async function readBlobJson<T>(pathname: string): Promise<T | null> {
  const base = blobBaseUrl()
  if (!base) return null

  try {
    const res = await fetch(`${base}/${pathname}?v=${BUILD_CACHE_BUSTER}`, {
      cache: 'force-cache',
    })
    if (!res.ok) return null
    return (await res.json()) as T
  } catch {
    return null
  }
}

function sortByNewest<T extends { created_at: string }>(items: T[]): T[] {
  return [...items].sort((a, b) => {
    const at = Date.parse(a.created_at) || 0
    const bt = Date.parse(b.created_at) || 0
    return bt - at
  })
}

export async function getBlogPosts(): Promise<BlogArticleSummary[]> {
  const index = await readBlobJson<BlogArticleSummary[]>(INDEX_BLOB_PATH)
  if (!Array.isArray(index)) return []
  return sortByNewest(index.filter((s) => Boolean(s?.slug)))
}

export async function getBlogPost(slug: string): Promise<BlogArticle | null> {
  return readBlobJson<BlogArticle>(postBlobPath(slug))
}

export async function getBlogSlugs(): Promise<string[]> {
  const posts = await getBlogPosts()
  return posts.map((post) => post.slug).filter(Boolean)
}
